### ISSUE TITLE
Добавить ссылку на демо страницы

### ISSUE THREAD

**Issue by tsvetkovamaria** [Kodonbaev/-html_group_8_homework_34_aktilek_kodonbaev#3]
Для облегчения просмотра вашей страницы, было бы здорово добавить сылку на уже сверстанную страницу (демо) в файл readme.md вашего репозитория. Тогда любой человек сможет зайтив репо, кликнуть на ссылку и посмотреть готовую работу в браузере, не клонируя репо локально. 

Можно добавить себе демо версию страницы через github pages

**Comment by Kodonbaev** [comment]
Добавил
